/// <reference path="../deno-types.d.ts" />

import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const TELEGRAM_BOT_TOKEN = Deno.env.get("TELEGRAM_BOT_TOKEN");
const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get(
  "SUPABASE_SERVICE_ROLE_KEY",
);

if (!TELEGRAM_BOT_TOKEN) {
  throw new Error("TELEGRAM_BOT_TOKEN is not configured");
}

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  throw new Error("Supabase environment variables are missing");
}

const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY,
);

const telegramApi = `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}`;

async function sendTelegramMessage(
  chatId: number | string,
  text: string,
) {
  const response = await fetch(`${telegramApi}/sendMessage`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      chat_id: chatId,
      text,
    }),
  });

  const result = await response.json();

  if (!response.ok || !result.ok) {
    console.error("Telegram sendMessage error:", result);

    throw new Error(
      result.description || "Failed to send Telegram message",
    );
  }

  return result;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      headers: corsHeaders,
    });
  }

  if (req.method !== "POST") {
    return new Response(
      JSON.stringify({
        error: "Method not allowed",
      }),
      {
        status: 405,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      },
    );
  }

  try {
    const update = await req.json();

    console.log(
      "Telegram update:",
      JSON.stringify(update),
    );

    /*
     * Telegram can send many types of updates.
     *
     * For XDerma we primarily care about:
     * - message
     * - edited_message
     */

    const message =
      update.message ??
      update.edited_message ??
      null;

    if (!message) {
      return new Response(
        JSON.stringify({
          ok: true,
          ignored: true,
          reason: "No message in update",
        }),
        {
          status: 200,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        },
      );
    }

    const telegramUser = message.from;
    const telegramChat = message.chat;

    if (!telegramUser || !telegramChat) {
      return new Response(
        JSON.stringify({
          ok: true,
          ignored: true,
          reason: "Missing Telegram user or chat",
        }),
        {
          status: 200,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        },
      );
    }

    const telegramUserId = String(telegramUser.id);
    const telegramChatId = String(telegramChat.id);

    const messageText =
      typeof message.text === "string"
        ? message.text.trim()
        : "";

    /*
     * ---------------------------------------------------------
     * SPECIALIST CONNECTION
     * ---------------------------------------------------------
     *
     * When a specialist first opens the bot and presses START,
     * Telegram sends:
     *
     * /start
     *
     * We use this to connect the Telegram account to the
     * specialist's XDerma account.
     *
     * The recommended format is:
     *
     * /start <connection_code>
     *
     * Example:
     *
     * /start xd_a82jd92
     *
     * The connection code should be generated by XDerma.
     */

    if (messageText.startsWith("/start")) {
      const parts = messageText.split(/\s+/);
      const connectionCode = parts[1];

      if (!connectionCode) {
        await sendTelegramMessage(
          telegramChatId,
          [
            "🩺 Welcome to XDerma Specialist Connect.",
            "",
            "To connect your Telegram account to XDerma, please open the XDerma app and use the \"Connect Telegram\" option.",
          ].join("\n"),
        );

        return new Response(
          JSON.stringify({
            ok: true,
            action: "start_without_code",
          }),
          {
            status: 200,
            headers: {
              ...corsHeaders,
              "Content-Type": "application/json",
            },
          },
        );
      }

      /*
       * Find the pending connection created by XDerma.
       *
       * This assumes we create a table:
       *
       * specialist_telegram_connections
       *
       * with:
       * - specialist_name
       * - connection_code
       * - telegram_user_id
       * - telegram_chat_id
       * - telegram_username
       * - connected_at
       */

      const { data: connection, error: connectionError } =
        await supabase
          .from("specialist_telegram_connections")
          .select("*")
          .eq("connection_code", connectionCode)
          .eq("status", "pending")
          .maybeSingle();

      if (connectionError) {
        console.error(
          "Connection lookup error:",
          connectionError,
        );

        throw connectionError;
      }

      if (!connection) {
        await sendTelegramMessage(
          telegramChatId,
          [
            "❌ This XDerma connection code is invalid or has expired.",
            "",
            "Please generate a new connection code from the XDerma app.",
          ].join("\n"),
        );

        return new Response(
          JSON.stringify({
            ok: true,
            action: "invalid_connection_code",
          }),
          {
            status: 200,
            headers: {
              ...corsHeaders,
              "Content-Type": "application/json",
            },
          },
        );
      }

      /*
       * Connect Telegram to the specialist.
       */

      const { error: updateError } = await supabase
        .from("specialist_telegram_connections")
        .update({
          telegram_user_id: telegramUserId,
          telegram_chat_id: telegramChatId,
          telegram_username:
            telegramUser.username ?? null,
          telegram_first_name:
            telegramUser.first_name ?? null,
          telegram_last_name:
            telegramUser.last_name ?? null,
          status: "connected",
          connected_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        })
        .eq("id", connection.id);

      if (updateError) {
        console.error(
          "Failed to save Telegram connection:",
          updateError,
        );

        throw updateError;
      }

      await sendTelegramMessage(
        telegramChatId,
        [
          "✅ XDerma Telegram connected successfully.",
          "",
          "You can now receive specialist consultation messages here.",
          "",
          "When a patient sends you a message through XDerma, it will appear in this Telegram chat.",
        ].join("\n"),
      );

      return new Response(
        JSON.stringify({
          ok: true,
          action: "telegram_connected",
          specialist_connection_id: connection.id,
        }),
        {
          status: 200,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        },
      );
    }

    /*
     * ---------------------------------------------------------
     * IGNORE NON-TEXT MESSAGES FOR NOW
     * ---------------------------------------------------------
     */

    if (!messageText) {
      await sendTelegramMessage(
        telegramChatId,
        "For now, XDerma specialist consultations support text messages. Image and file support can be added next.",
      );

      return new Response(
        JSON.stringify({
          ok: true,
          ignored: true,
          reason: "Non-text message",
        }),
        {
          status: 200,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        },
      );
    }

    /*
     * ---------------------------------------------------------
     * FIND SPECIALIST
     * ---------------------------------------------------------
     */

    const { data: connection, error: specialistError } =
      await supabase
        .from("specialist_telegram_connections")
        .select("*")
        .eq("telegram_user_id", telegramUserId)
        .eq("status", "connected")
        .maybeSingle();

    if (specialistError) {
      console.error(
        "Specialist lookup error:",
        specialistError,
      );

      throw specialistError;
    }

    if (!connection) {
      await sendTelegramMessage(
        telegramChatId,
        [
          "⚠️ Your Telegram account is not connected to an XDerma specialist account.",
          "",
          "Please open XDerma and connect your Telegram account first.",
        ].join("\n"),
      );

      return new Response(
        JSON.stringify({
          ok: true,
          action: "specialist_not_connected",
        }),
        {
          status: 200,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        },
      );
    }

    await sendTelegramMessage(
      telegramChatId,
      [
        "Your XDerma Telegram account is connected.",
        "",
        "Incoming consultation routing is not configured in this project schema yet.",
      ].join("\n"),
    );

    /*
     * ---------------------------------------------------------
     * RESPONSE
     * ---------------------------------------------------------
     */

    return new Response(
      JSON.stringify({
        ok: true,
        action: "specialist_message_received",
        specialist_connection_id: connection.id,
      }),
      {
        status: 200,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      },
    );
  } catch (error) {
    console.error(
      "Telegram webhook error:",
      error,
    );

    return new Response(
      JSON.stringify({
        ok: false,
        error:
          error instanceof Error
            ? error.message
            : "Internal server error",
      }),
      {
        status: 500,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      },
    );
  }
});
