create table if not exists public.account_verification_codes (
  id bigint generated by default as identity primary key,
  email text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists account_verification_codes_email_verified_idx
  on public.account_verification_codes (email, verified);

create index if not exists account_verification_codes_expires_at_idx
  on public.account_verification_codes (expires_at);
